# Generated by Django 3.1.1 on 2020-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0002_remove_book_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.FileField(default='empty.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Anonymus', max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='No name', max_length=25),
        ),
    ]
