# Generated by Django 3.1.1 on 2020-09-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0003_auto_20200913_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
        migrations.AddField(
            model_name='book',
            name='image_id',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
