# Generated by Django 3.1.1 on 2020-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0004_auto_20200913_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_format',
            field=models.CharField(default='jpg', max_length=6),
        ),
    ]
